Description: Stack para criar um par창metro no Parameter Store

Parameters:
  ParameterName:
    Type: String
    Description: Nome do par창metro
    Default: "/config/spring-boot-localstack_localstack/helloWorld"
  ParameterValue:
    Type: String
    Description: Valor do par창metro
    Default: "Hello World Parameter Store"
Resources:
  MyParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Ref ParameterName
      Type: String
      Value: !Ref ParameterValue
      Description: Par창metro criado pelo CloudFormation


