Description: Stack para criar parâmetros no Secret Manager

Parameters:
  SecretName:
    Type: String
    Description: Nome do segredo
    Default: "/secret/spring-boot-localstack_localstack"
  SecretDescription:
    Type: String
    Description: Descrição do segredo
    Default: A secret for my application
  SecretValue:
    Type: String
    Description: Valor do segredo
    NoEcho: true
    Default: "{\"valor1\":\"Oi Mundo\",\"valor2\":\"Hello World\",\"valor3\":\"Hola Mundo\"}"


Resources:
  MySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Join ["", [!Ref SecretName]]
      Description: !Ref SecretDescription
      SecretString: !Ref SecretValue